galaxy_info:
  description: Role for collecting EC2 tags
  license: GPLv2
  min_ansible_version: 2.0 (needed for executing by proxy)
  platforms: Amazon Linux
  galaxy_tags: []
dependencies: []
