############
# Filebeat #
############
filebeat_pulp_user             : filebeat
filebeat_pulp_password         : Passw0rd

##########
# Nessus #
##########
pulp_user_nessus     : nessus
pulp_password_nessus : Passw0rd
mgr_user_nessus      : npa.example.nessus
mgr_creds_nessus     : Passw0rd

################
# Amazon Repos #
################
pulp_user_amzn     : pulp
pulp_password_amzn : Passw0rd

##########
# Icinga #
##########
icinga_user             : icinga
icinga_password         : "0123456789ABCDEF@#"

#########################
# Credentials APPSERVER #
#########################
appserver_mariadb:
    root_password                           : Passw0rd
    user                                    : appserver
    password                                : Passw0rd
    user_backups                            : root

##########################
# SERVICIO SES (EMAIL)   #
##########################
SES_USER                     : AKIAIOSFODNN7EXAMPLE
SES_PASSWORD                 : wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

###################
# Credentials API #
###################
frontend:
  backend:
    url       : "https://api.{{ dnszone }}"
    base      : "api/v1"
