---

- service: >
    name=atd
    state=stopped
    enabled=no
  when: ansible_distribution != 'CentOS'

- service: >
    name=netfs
    state=stopped
    enabled=no
  when: ansible_distribution != 'CentOS'

- service: >
    name=nfs
    state=stopped
    enabled=no

- service: >
    name=rpcbind
    state=stopped
    enabled=no
